# Generated by Django 4.2.3 on 2023-07-07 16:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=150, validators=[django.core.validators.EmailValidator])),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Your phone number must contain optional country code, optional parentheses for the area code, and separators between digits', regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('Address', models.CharField(max_length=100)),
                ('Zip_code', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Your zip-code must contain five digits, with an optional hyphen followed by four more digits. Valid examples include '12345' and '98765-4321'.", regex='^[0-9]{5}(?:-[0-9]{4})?$')], verbose_name='Zip Code')),
                ('City', models.CharField(max_length=34)),
                ('Country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to='product_images/main/')),
                ('first_image', models.ImageField(upload_to='product_images/')),
                ('second_image', models.ImageField(upload_to='product_images/')),
                ('third_image', models.ImageField(upload_to='product_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=9999.99, max_digits=8)),
                ('description', models.TextField(blank=True, default='product description...')),
                ('Release_date', models.DateField(auto_now=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='audiophile_store.category')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiophile_store.product_images')),
            ],
        ),
        migrations.CreateModel(
            name='Cart_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('created', models.DateField(auto_now=True)),
                ('modified', models.DateField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiophile_store.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiophile_store.product')),
            ],
        ),
    ]
