# Generated by Django 4.2.3 on 2023-07-06 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audiophile_store', '0002_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('created', models.DateField(auto_now=True)),
                ('modified', models.DateField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiophile_store.cart')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='Release_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Cart_Add',
        ),
        migrations.AddField(
            model_name='cart_item',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiophile_store.product'),
        ),
    ]
