# Generated by Django 4.2.3 on 2023-07-11 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audiophile_store', '0002_alter_cart_item_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
